In [3]:
import scipy.io as sio
import numpy as np

In [4]:
import scipy

In [ ]:
#mat_contents = sio.loadmat('XRMBsJW11.mat')

In [5]:
M_T=np.array([[4,2,14,3,13,7],[5,1,4,7,0,4],[1,9,8,12,5,1]])

In [6]:
M=np.transpose(M_T)

In [7]:
M


array([[ 4,  5,  1],
       [ 2,  1,  9],
       [14,  4,  8],
       [ 3,  7, 12],
       [13,  0,  5],
       [ 7,  4,  1]])

In [11]:
mean=[1,2,3]
I=[[1,0,0],[0,1,0],[0,0,1]]
Z=np.random.multivariate_normal(mean,I,50000)

In [12]:
X=np.dot(M,np.transpose(Z))

In [13]:
X

array([[ 13.66414891,  25.80833811,  12.58414132, ...,  12.11884018,
         10.36049953,  15.96553655],
       [ 34.27164673,  46.89811552,  30.81581227, ...,  18.53546447,
         38.48620771,  45.55721468],
       [ 49.51806438,  79.65605867,  38.34273548, ...,  16.22831998,
         26.59152094,  54.21752283],
       [ 51.85298308,  76.16131039,  49.59487691, ...,  39.1133015 ,
         63.10155165,  70.5861698 ],
       [ 33.95678281,  54.90572156,  22.50481509, ...,   0.81227878,
          6.27383891,  32.58135988],
       [ 16.55981167,  31.14844365,  12.6785356 , ...,   7.50628833,
          4.70076202,  16.34189222]])

In [14]:
np.array([1,2,3,4,5,6])*10000

array([10000, 20000, 30000, 40000, 50000, 60000])

In [17]:
X[1,:]=[1,2,3,4,5]*10000

In [18]:
X

array([[ 13.66414891,  25.80833811,  12.58414132, ...,  12.11884018,
         10.36049953,  15.96553655],
       [  1.        ,   2.        ,   3.        , ...,   3.        ,
          4.        ,   5.        ],
       [ 49.51806438,  79.65605867,  38.34273548, ...,  16.22831998,
         26.59152094,  54.21752283],
       [ 51.85298308,  76.16131039,  49.59487691, ...,  39.1133015 ,
         63.10155165,  70.5861698 ],
       [ 33.95678281,  54.90572156,  22.50481509, ...,   0.81227878,
          6.27383891,  32.58135988],
       [ 16.55981167,  31.14844365,  12.6785356 , ...,   7.50628833,
          4.70076202,  16.34189222]])

In [19]:
s,v,d=np.linalg.svd(X,full_matrices=False)

In [21]:
top_s_3=s[:,0:3]

In [22]:
top_s_3

array([[-0.21360843,  0.00268817,  0.69938945],
       [-0.03451755, -0.03407038,  0.00211698],
       [-0.58601904,  0.32837489, -0.07560913],
       [-0.64990105, -0.70595021, -0.15308385],
       [-0.36567808,  0.58032502, -0.3824319 ],
       [-0.23166749,  0.23634527,  0.57917559]])

In [ ]:
Z1=np.random.multivariate_normal(mean,I,50000)
Z2=np.random.multivariate_normal(mean,I,50000)
Z3=np.random.multivariate_normal(mean,I,50000)
X1=np.dot(M,np.transpose(Z1))