In [1]:
import scipy.io as sio
import numpy as np

In [2]:
mat_contents = sio.loadmat('XRMBsJW11.mat')

In [3]:
training=mat_contents['data']['training']

In [4]:
training

array([[ array([[  1.60736133e+00,   1.76238103e+00,   1.91181819e+00, ...,
          2.62125971e+00,   2.55492226e+00,   2.33119249e+00],
       [ -8.28977098e-01,  -1.03051527e+00,  -1.15407743e+00, ...,
         -1.36306349e+00,  -1.42738481e+00,  -1.04358030e+00],
       [ -1.27252980e+00,  -1.44035731e+00,  -1.43888158e+00, ...,
         -2.04234858e+00,  -1.71737394e+00,  -1.40715320e+00],
       ..., 
       [  1.62618704e-01,   6.57645799e-01,   9.98323576e-01, ...,
          3.34570904e-01,   6.10561735e-01,   8.56548020e-01],
       [  4.01236926e-01,  -8.15103097e-02,  -5.52644872e-01, ...,
          9.28927525e-01,   3.92883340e-01,   7.68751476e-03],
       [ -1.25957024e-03,  -1.47191460e-02,  -1.59240987e-01, ...,
          4.85736642e-01,   4.02250345e-01,   2.90651715e-01]])]], dtype=object)

In [5]:
len(training)

1

In [6]:
training[0]

array([ array([[  1.60736133e+00,   1.76238103e+00,   1.91181819e+00, ...,
          2.62125971e+00,   2.55492226e+00,   2.33119249e+00],
       [ -8.28977098e-01,  -1.03051527e+00,  -1.15407743e+00, ...,
         -1.36306349e+00,  -1.42738481e+00,  -1.04358030e+00],
       [ -1.27252980e+00,  -1.44035731e+00,  -1.43888158e+00, ...,
         -2.04234858e+00,  -1.71737394e+00,  -1.40715320e+00],
       ..., 
       [  1.62618704e-01,   6.57645799e-01,   9.98323576e-01, ...,
          3.34570904e-01,   6.10561735e-01,   8.56548020e-01],
       [  4.01236926e-01,  -8.15103097e-02,  -5.52644872e-01, ...,
          9.28927525e-01,   3.92883340e-01,   7.68751476e-03],
       [ -1.25957024e-03,  -1.47191460e-02,  -1.59240987e-01, ...,
          4.85736642e-01,   4.02250345e-01,   2.90651715e-01]])], dtype=object)

In [7]:
len(training[0][0])

39

In [8]:
len(np.transpose(training[0][0]))

8527

In [9]:
mat_contents['Phones']

array([[ ([[array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), array([u'"AE"'], 
      dtype='<U4'), 

In [10]:
len(mat_contents['Phones'][0][0][0][0])

8527

In [11]:
phones=mat_contents['Phones'][0][0][0][0]

In [12]:
phones[0]

array([u'"AE"'], 
      dtype='<U4')

In [13]:
phones[0][0]

u'"AE"'

In [14]:
training_1=training[0][0]

In [15]:
len(training_1)

39

In [16]:
phones

array([array([u'"AE"'], 
      dtype='<U4'),
       array([u'"AE"'], 
      dtype='<U4'),
       array([u'"AE"'], 
      dtype='<U4'), ...,
       array([u'"EH"'], 
      dtype='<U4'),
       array([u'"EH"'], 
      dtype='<U4'),
       array([u'"EH"'], 
      dtype='<U4')], dtype=object)

In [17]:
len(phones)

8527

In [18]:
phones_training=mat_contents['Phones']['training']

In [19]:
phones_training

array([[ array([[array([u'"AE"'], 
      dtype='<U4'),
        array([u'"AE"'], 
      dtype='<U4'),
        array([u'"AE"'], 
      dtype='<U4'), ...,
        array([u'"EH"'], 
      dtype='<U4'),
        array([u'"EH"'], 
      dtype='<U4'),
        array([u'"EH"'], 
      dtype='<U4')]], dtype=object)]], dtype=object)

In [20]:
len(phones_training[0][0][0])

8527

In [21]:
phones_training[0][0][0]

array([array([u'"AE"'], 
      dtype='<U4'),
       array([u'"AE"'], 
      dtype='<U4'),
       array([u'"AE"'], 
      dtype='<U4'), ...,
       array([u'"EH"'], 
      dtype='<U4'),
       array([u'"EH"'], 
      dtype='<U4'),
       array([u'"EH"'], 
      dtype='<U4')], dtype=object)

In [22]:
phones_training_list=phones_training[0][0][0].tolist()

In [23]:
phones_training_list

[array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
       dtype='<U4'), array([u'"AE"'], 
      

In [24]:
phones_training_list.index(np.array([u'"AE"'], dtype='<U4'))

0

In [25]:
training_1

array([[  1.60736133e+00,   1.76238103e+00,   1.91181819e+00, ...,
          2.62125971e+00,   2.55492226e+00,   2.33119249e+00],
       [ -8.28977098e-01,  -1.03051527e+00,  -1.15407743e+00, ...,
         -1.36306349e+00,  -1.42738481e+00,  -1.04358030e+00],
       [ -1.27252980e+00,  -1.44035731e+00,  -1.43888158e+00, ...,
         -2.04234858e+00,  -1.71737394e+00,  -1.40715320e+00],
       ..., 
       [  1.62618704e-01,   6.57645799e-01,   9.98323576e-01, ...,
          3.34570904e-01,   6.10561735e-01,   8.56548020e-01],
       [  4.01236926e-01,  -8.15103097e-02,  -5.52644872e-01, ...,
          9.28927525e-01,   3.92883340e-01,   7.68751476e-03],
       [ -1.25957024e-03,  -1.47191460e-02,  -1.59240987e-01, ...,
          4.85736642e-01,   4.02250345e-01,   2.90651715e-01]])

In [26]:
len(training_1)

39

In [27]:
len(np.transpose(training_1))

8527

In [28]:
AE=training_1[:,0:1173]

In [29]:
AA=training_1[:,7227:7808]

In [30]:
UW=training_1[:,4670:5623]
IY=training_1[:,5623:7226]

In [31]:
aeaa=np.column_stack((AE,AA))

In [32]:
len(np.transpose(aeaa))

1754

In [33]:
uwiy=np.column_stack((UW,IY))

In [34]:
uwiy

array([[ 0.14867342,  0.39219592,  0.39782266, ...,  0.31979648,
        -0.15048674, -0.45703941],
       [ 1.62726471,  1.62409991,  1.74770056, ...,  0.41710661,
         0.40259311,  0.61460621],
       [ 1.13925007,  1.08132357,  1.15507102, ...,  1.78700392,
         1.30500885,  0.27476677],
       ..., 
       [ 1.0136112 ,  0.79972847,  0.45372878, ..., -1.51215165,
        -0.94067582, -0.39319422],
       [ 1.64534602,  1.69631954,  1.3341852 , ...,  0.81617328,
         0.9677412 ,  0.89452425],
       [ 0.1494238 ,  0.98423932,  1.58023004, ...,  0.74962252,
         0.31101923,  0.06387591]])

In [35]:
len(np.transpose(uwiy))

2556

In [36]:
from sklearn.decomposition import PCA

In [37]:
pca=PCA(n_components=2)

In [38]:
pca=pca.fit(np.transpose(aeaa))

In [39]:
vector1=pca.components_[0]
vector2=pca.components_[1]

In [40]:
pca.components_

array([[ 0.00836114, -0.07553768,  0.08860591,  0.17809177, -0.12805301,
        -0.18303362,  0.21399504,  0.12440824, -0.31876764, -0.02127571,
         0.23028039, -0.22789013,  0.0350001 , -0.34517565,  0.12280738,
         0.34961648,  0.00804065,  0.03040874, -0.14761205, -0.17157861,
        -0.1731455 ,  0.25321299,  0.06687731,  0.20141751,  0.0213041 ,
        -0.10295854, -0.02760099,  0.01253505, -0.01658153, -0.08423212,
         0.0799643 ,  0.17233567, -0.13102292, -0.14236228,  0.2175374 ,
        -0.02746681, -0.16245039,  0.14169987,  0.00073825],
       [-0.00139665, -0.05419467,  0.16939643,  0.14653529, -0.21927152,
        -0.16169757,  0.20982305,  0.06316271, -0.20616177,  0.08664029,
         0.1413454 , -0.31516849,  0.07793307,  0.39805968, -0.08775089,
        -0.3754458 , -0.10464848, -0.04293854,  0.2332532 ,  0.20200055,
         0.06119945, -0.21317335, -0.08753102, -0.13800603, -0.04765111,
        -0.00954038, -0.02448066, -0.00740301, -0.0773993 , -0.

In [41]:
u1,s1,v1=np.linalg.svd(aeaa,full_matrices=False)
u2,s2,v2=np.linalg.svd(uwiy,full_matrices=False)

In [42]:
#projection_aeaa=np.dot(pca.components_,np.transpose(aeaa))
u1

array([[-0.41327458,  0.05142752, -0.0456259 , ..., -0.0764964 ,
        -0.12031617,  0.59958571],
       [ 0.05786788,  0.0589887 , -0.04825994, ..., -0.15857197,
         0.05332567,  0.2086937 ],
       [ 0.41641565, -0.13752802,  0.21936874, ...,  0.00906817,
         0.32794213,  0.42290991],
       ..., 
       [-0.10675002,  0.18232925, -0.06395044, ...,  0.04808145,
        -0.26405856,  0.09751188],
       [-0.03376868, -0.12896308,  0.23321175, ...,  0.00399343,
        -0.10187797,  0.08994109],
       [-0.00613546, -0.00159208, -0.02796606, ...,  0.02039994,
        -0.14181522,  0.05510294]])

In [43]:
u1=u1[:,0:2]
u2=u2[:,0:2]

In [44]:
u1

array([[-0.41327458,  0.05142752],
       [ 0.05786788,  0.0589887 ],
       [ 0.41641565, -0.13752802],
       [-0.02920294, -0.16703353],
       [ 0.18082609,  0.09364437],
       [-0.20475973,  0.20085858],
       [-0.36327981, -0.15743482],
       [-0.20747652, -0.09223139],
       [ 0.2471415 ,  0.26854752],
       [ 0.17692981,  0.00458428],
       [ 0.20571323, -0.25532463],
       [ 0.1071204 ,  0.20004042],
       [-0.03507249, -0.02727939],
       [ 0.02189987,  0.3724783 ],
       [-0.00740157, -0.12834105],
       [ 0.01759618, -0.38160894],
       [-0.03397603, -0.00903539],
       [-0.02859902, -0.02832181],
       [ 0.03902261,  0.15656999],
       [ 0.00680081,  0.18008192],
       [-0.05270644,  0.18663082],
       [ 0.04003022, -0.27291049],
       [ 0.03540145, -0.0842918 ],
       [-0.00702673, -0.20359001],
       [-0.01566952, -0.0189696 ],
       [-0.0123812 ,  0.09960027],
       [ 0.27570868, -0.02655497],
       [-0.06834695,  0.00577852],
       [-0.26388767,

In [45]:
projection_aeaa=np.dot(np.transpose(u1),aeaa)
projection_uwiy=np.dot(np.transpose(u2),uwiy)

In [46]:
import matplotlib.pyplot as plt
plt.plot(projection_aeaa[0],projection_aeaa[1],'bs')
plt.plot(projection_uwiy[0],projection_uwiy[1],'rs')

In [47]:
plt.show()

In [48]:
np.array([[1,2],[2,3]])++2

array([[3, 4],
       [4, 5]])

In [49]:
total_data=np.column_stack((aeaa,uwiy))

In [50]:
len(np.transpose(total_data))

4310

In [51]:
u,s,v=np.linalg.svd(total_data)

In [52]:
u=u[:,0:2]

In [53]:
projection1=np.dot(np.transpose(u),aeaa)

In [54]:
projection2=np.dot(np.transpose(u),uwiy)

In [55]:
plt.plot(projection1[0],projection1[1],'bs')
plt.plot(projection2[0],projection2[1],'rs')

In [56]:
plt.show()

In [57]:
np.dot(np.array([1,2]),np.array([2,3]))

8

In [70]:
def kernel1(x,y,c):
    temp=np.dot(x,y)
    return (temp+c)**2

In [71]:
temp=np.dot(np.transpose(total_data),total_data)

In [72]:
type(temp)

numpy.ndarray

In [73]:
kernel1=(temp+2)**2

In [74]:
ku,ks,kv=np.linalg.svd(kernel1,full_matrices=False)

In [75]:
ku_1=ku[:,0:2]

In [76]:
np.array([1,2,3])*np.array([1,2,4])

array([ 1,  4, 12])

In [77]:
#as for the training_data
def returnkernel1(matrix1,dataset):
    temp=np.dot(matrix1,dataset)
    return (temp+2)**2

In [78]:
kpro1_m=returnkernel1(np.transpose(total_data),aeaa)
kpro2_m=returnkernel1(np.transpose(total_data),uwiy)

In [79]:
kpro1=np.dot(np.transpose(ku_1),kpro1_m)
kpro2=np.dot(np.transpose(ku_1),kpro2_m)

In [80]:
plt.plot(kpro1[0],kpro1[1],'bs')
plt.plot(kpro2[0],kpro2[1],'rs')

In [81]:
plt.show()

In [150]:
testing_data=mat_contents['data']['testing']

In [156]:
testing_1=testing_data[0][0]

In [157]:
ae_testing=testing_1[:,0:375]
aa_testing=testing_1[:,2443:2706]
uw_testing=testing_1[:,1382:1578]
iy_testing=testing_1[:,1578:2443]

In [158]:
aaae_testing=np.column_stack((ae_testing,aa_testing))
uwiy_testing=np.column_stack((uw_testing,iy_testing))

In [161]:
kpro1_m_testing=returnkernel1(np.transpose(total_data),aaae_testing)
kpro2_m_testing=returnkernel1(np.transpose(total_data),uwiy_testing)


In [162]:
kpro1_testing=np.dot(np.transpose(ku_1),kpro1_m_testing)
kpro2_testing=np.dot(np.transpose(ku_1),kpro2_m_testing)

In [163]:
plt.plot(kpro1_testing[0],kpro1_testing[1],'bs')
plt.plot(kpro2_testing[0],kpro2_testing[1],'rs')

In [164]:
plt.show()

In [202]:
import scipy
from scipy.spatial.distance import pdist, squareform
  # this is an NxD matrix, where N is number of items and D its dimensionalites
X = np.transpose(total_data) 
pairwise_dists = squareform(pdist(X, 'euclidean'))
K = scipy.exp(-pairwise_dists ** 2 / float(30))
            

In [203]:
len(K)

4311

In [204]:
q,w,e=scipy.linalg.svd(K,full_matrices=False)

In [206]:
q=q[:,0:2]


In [207]:
q

array([[-0.02739013, -0.01321154],
       [-0.03079811, -0.01773644],
       [-0.03300966, -0.01947431],
       ..., 
       [-0.01337546,  0.01780946],
       [-0.01415513,  0.00534176],
       [-0.01654816,  0.00316271]])

In [208]:
len(np.transpose(aeaa))

1754

In [212]:
proj_g1=np.dot(np.transpose(q),K[:,0:1754])
proj_g2=np.dot(np.transpose(q),K[:,1754:4311])

In [213]:
plt.plot(proj_g1[0],proj_g1[1],'bs')
plt.plot(proj_g2[0],proj_g2[1],'rs')

In [214]:
plt.show()

In [82]:
print ku_1

[[-0.00423189 -0.01400486]
 [-0.00522845 -0.01833897]
 [-0.00545721 -0.0191198 ]
 ..., 
 [-0.00926804 -0.00110577]
 [-0.00636912 -0.00222609]
 [-0.0044898  -0.00233096]]


In [83]:
print kernel1

[[  1.19062240e+03   1.12243301e+03   9.17828075e+02 ...,   1.31438512e+01
    1.36205716e-01   4.04116517e+01]
 [  1.12243301e+03   1.26311496e+03   1.11307109e+03 ...,   9.20590982e+00
    3.42007272e-01   4.54103726e+01]
 [  9.17828075e+02   1.11307109e+03   1.16290741e+03 ...,   4.61848737e-02
    1.73577722e+01   1.49359429e+01]
 ..., 
 [  1.31438512e+01   9.20590982e+00   4.61848737e-02 ...,   2.22766003e+03
    1.47525096e+03   9.10820595e+02]
 [  1.36205716e-01   3.42007272e-01   1.73577722e+01 ...,   1.47525096e+03
    1.62018436e+03   1.21089831e+03]
 [  4.04116517e+01   4.54103726e+01   1.49359429e+01 ...,   9.10820595e+02
    1.21089831e+03   1.57192155e+03]]


In [84]:
print ku

[[-0.00423189 -0.01400486  0.00157016 ...,  0.01892495 -0.018281
   0.01456305]
 [-0.00522845 -0.01833897  0.00284333 ...,  0.05312355 -0.04203921
   0.0602037 ]
 [-0.00545721 -0.0191198   0.00285487 ..., -0.06636295  0.02622691
  -0.05852539]
 ..., 
 [-0.00926804 -0.00110577  0.01108884 ...,  0.0083524   0.00139238
   0.00445299]
 [-0.00636912 -0.00222609  0.0058126  ...,  0.00139455  0.02447959
  -0.00277961]
 [-0.0044898  -0.00233096 -0.00150086 ..., -0.01358507 -0.01869945
  -0.01364278]]


In [86]:
print ks

[  1.43239519e+06   7.89370665e+05   6.49578649e+05 ...,   4.83418385e-11
   2.85239369e-11   1.06370837e-11]


In [87]:
import numpy as np
import scipy as sp
import scipy.io as sio
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA, KernelPCA

data_set = sio.loadmat('XRMBsJW11.mat')

training = data_set['data']['training']
testing = data_set['data']['testing'] 
training_clean = training[0][0]
testing_clean = testing[0][0]

#AE index 0-1172
AE = np.array(training_clean[:,0:1172])
#AA index 7227-7806
AA = np.array(training_clean[:,7227:7806])
#UW index 4670-5622
UW = np.array(training_clean[:,4670:5622])
#IY index 5623-7226
IY = np.array(training_clean[:,5623:7226])

AEAA = np.column_stack((AE,AA))
UWIY = np.column_stack((UW,IY))

combdata = np.column_stack((AEAA,UWIY))

#<x,y>
covxy = np.dot(np.transpose(combdata), combdata)
kprojA = np.dot(np.transpose(combdata), AEAA)
kprojB = np.dot(np.transpose(combdata), UWIY)


#(<x,y> + 2)^2
kernel = (np.dot(np.transpose(combdata),combdata) + 2)**2
kerpA = (kprojA + 2)**2
kerpB = (kprojB + 2)**2

U , A, V = sp.linalg.svd(kernel, full_matrices=False)

sv = np.array(U[:,0:2])

seta = np.dot(np.transpose(sv), kerpA)
setu = np.dot(np.transpose(sv), kerpB)

plt.plot(seta[0],seta[1],'bs')
plt.plot(setu[0],setu[1],'rs')
plt.show()